BEGIN;

ALTER TABLE posts ADD COLUMN IF NOT EXISTS event_type TEXT;
ALTER TABLE posts ADD COLUMN IF NOT EXISTS organized_by TEXT;
ALTER TABLE posts ADD COLUMN IF NOT EXISTS event_start_date TIMESTAMPTZ;
ALTER TABLE posts ADD COLUMN IF NOT EXISTS event_end_date TIMESTAMPTZ;
ALTER TABLE posts ADD COLUMN IF NOT EXISTS location TEXT;
ALTER TABLE posts ADD COLUMN IF NOT EXISTS highlight TEXT;
ALTER TABLE posts ADD COLUMN IF NOT EXISTS short_description TEXT;
ALTER TABLE posts ADD COLUMN IF NOT EXISTS detailed_experience TEXT;
ALTER TABLE posts ADD COLUMN IF NOT EXISTS tech_stack_json JSONB NOT NULL DEFAULT '[]'::jsonb;
ALTER TABLE posts ADD COLUMN IF NOT EXISTS team_members_json JSONB NOT NULL DEFAULT '[]'::jsonb;
ALTER TABLE posts ADD COLUMN IF NOT EXISTS project_link TEXT;
ALTER TABLE posts ADD COLUMN IF NOT EXISTS certificate_url TEXT;
ALTER TABLE posts ADD COLUMN IF NOT EXISTS images_json JSONB NOT NULL DEFAULT '[]'::jsonb;

COMMIT;
